version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.0

jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    working_directory: .
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: Build ViteJS App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: ubuntu:20.04
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI setup dependencies
          command: |
            apt-get update && apt-get install -y curl unzip
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: Look in Directory
          command: ls -ltr
      - run:
          name: Create Build Folder with Git SHA
          command: mkdir -p build_$CIRCLE_SHA1 && mv dist/* build_$CIRCLE_SHA1
      # - run:
      #     name: Rename Build Folder with Git SHA
      #     command: |
      #       export GIT_SHA=$(git rev-parse --short HEAD)
      #       mv dist "build_${GIT_SHA}"
      #       echo "export BUILD_DIR=build_${GIT_SHA}" >> $BASH_ENV
      - run:
          name: Look in Directory
          command: ls -ltr
      - run:
          name: Deploy to S3
          command: |
            aws s3 cp --recursive "./build_${CIRCLE_SHA1}" "s3://iodev-aws-cci-poc/prod_live/build_${CIRCLE_SHA1}/"
            aws s3 cp --recursive "./build_${CIRCLE_SHA1}" "s3://iodev-aws-cci-poc/prod_live/current/"
      - run:
          name: Invalidate CloudFront Cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
